export const AIRPLANE_LIST_REQUEST ='AIRPLANE_LIST_REQUEST';
export const AIRPLANE_LIST_SUCCESS ='AIRPLANE_LIST_SUCCESS';
export const AIRPLANE_LIST_FAIL ='AIRPLANE_LIST_FAIL';

export const AIRPLANE_DETAILS_REQUEST ='AIRPLANE_DETAILS_REQUEST';
export const AIRPLANE_DETAILS_SUCCESS ='AIRPLANE_DETAILS_SUCCESS';
export const AIRPLANE_DETAILS_FAIL ='AIRPLANE_DETAILS_FAIL';

export const AIRPLANE_SAVE_REQUEST = 'AIRPLANE_SAVE_REQUEST';
export const AIRPLANE_SAVE_SUCCESS = 'AIRPLANE_SAVE_SUCCESS';
export const AIRPLANE_SAVE_FAIL = 'AIRPLANE_SAVE_FAIL';

export const AIRPLANE_DELETE_REQUEST = 'AIRPLANE_DELETE_REQUEST';
export const AIRPLANE_DELETE_SUCCESS = 'AIRPLANE_DELETE_SUCCESS';
export const AIRPLANE_DELETE_FAIL = 'AIRPLANE_DELETE_FAIL';

export const AIRPLANE_REVIEW_CREATE_REQUEST = 'AIRPLANE_REVIEW_CREATE_REQUEST';
export const AIRPLANE_REVIEW_CREATE_SUCCESS = 'AIRPLANE_REVIEW_CREATE_SUCCESS';
export const AIRPLANE_REVIEW_CREATE_FAIL = 'AIRPLANE_REVIEW_CREATE_FAIL';
export const AIRPLANE_REVIEW_CREATE_RESET = 'AIRPLANE_REVIEW_CREATE_RESET';

export const AIRPLANE_CATEGORY_REQUEST = 'AIRPLANE_CATEGORY_REQUEST';
export const AIRPLANE_CATEGORY_SUCCESS= 'AIRPLANE_CATEGORY_SUCCESS';
export const AIRPLANE_CATEGORY_FAIL= 'AIRPLANE_CATEGORY_FAIL';
