export const STAFF_LIST_REQUEST ='STAFF_LIST_REQUEST';
export const STAFF_LIST_SUCCESS ='STAFF_LIST_SUCCESS';
export const STAFF_LIST_FAIL ='STAFF_LIST_FAIL';

export const STAFF_DETAILS_REQUEST ='STAFF_DETAILS_REQUEST';
export const STAFF_DETAILS_SUCCESS ='STAFF_DETAILS_SUCCESS';
export const STAFF_DETAILS_FAIL ='STAFF_DETAILS_FAIL';

export const STAFF_SAVE_REQUEST = 'STAFF_SAVE_REQUEST';
export const STAFF_SAVE_SUCCESS = 'STAFF_SAVE_SUCCESS';
export const STAFF_SAVE_FAIL = 'STAFF_SAVE_FAIL';

export const STAFF_DELETE_REQUEST = 'STAFF_DELETE_REQUEST';
export const STAFF_DELETE_SUCCESS = 'STAFF_DELETE_SUCCESS';
export const STAFF_DELETE_FAIL = 'STAFF_DELETE_FAIL';


